import Head from "next/head";
import styles from "../styles/Home.module.css";
import Frame from "../components/Frame";
import Header from "../components/Header";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>resumecreator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <Header /> */}
        <Frame></Frame>
      </main>

      <footer className={styles.footer}>built by Fanny reslow</footer>
    </div>
  );
}
